# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: CI
  displayName: CI Stage
  jobs:
  - job: build
    displayName: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        yarn build
      displayName: 'yarn build'

- stage: CD
  displayName: CD Stage
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: Docs
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo This is a DEPLOYMENT job
            displayName: 'Deploy project'
